<?php if($block->isModuleEnabled() == 1){ ?>
    <table> 
        <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Image path</th>
        </thead>
    <tbody>
<?php
        $ids = [1,2,3];
        $categoryProducts = $block->getProductCollectionByCategories($ids);
        foreach ($categoryProducts as $product) {
            echo'
                <tr>
                <td> '.$product->getId().'</td>
                <td>'. $product->getName().' </td>
                <td> '.$product->getDescription().'</td>
                <td>'.$product->getImage().' </td>
                </tr>
                ';
        }
        
    }else echo '<h1>This configuration is off, check on the admin section.</h1>';
    ?>
    </tbody>
</table>

